### ISSUE TITLE
dependency on cmake

### ISSUE THREAD

**Issue by jorisr21** [doe300/cpplog#1]
In commit cb1a0923d25dbaad636cb4b91ecb3687c1f0e29e you increase cmake depencency on from 3.1 to 3.13. I adjusted this to 3.7 because I can't easily get higher than 3.7 on stretch, and I got it to compile correctly (as far as I can see).
Is it possible you didn't test the intermediate versions?
I'm trying to build VC4* on stretch.

**Comment by doe300** [comment]
Not sure how you got it working, but the CMake command `target_link_options` was introduced in [CMake 3.13](https://cmake.org/cmake/help/latest/release/3.13.html#commands), which is why it is the required version.

**Comment by jorisr21** [comment]
I found the target_link_options command within an if(ENABLE_SANITIZERS), and this is by default off. I guess that's why I didn't have a problem. Thanks.
